export const DASHBOARD_QUOTES = [
  "Opportunities don't happen, you create them.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The future depends on what you do today.",
  "Don't watch the clock; do what it does. Keep going.",
  "Quality means doing it right when no one is looking.",
  "Your career is a marathon, not a sprint.",
  "Strive not to be a success, but rather to be of value.",
  "The only way to do great work is to love what you do.",
  "Doubt kills more dreams than failure ever will.",
  "Action is the foundational key to all success.",
  "Don't be afraid to give up the good to go for the great.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success usually comes to those who are too busy to be looking for it.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "Great things are not done by impulse, but by a series of small things brought together.",
  "Believe you can and you're halfway there.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "It is never too late to be what you might have been.",
  "What comes easy won't last, and what lasts won't come easy.",
  "The expert in anything was once a beginner.",
  "A year from now you may wish you had started today.",
  "Focus on being productive instead of busy.",
  "Continuous improvement is better than delayed perfection.",
  "Small daily improvements over time lead to stunning results.",
  "There are no shortcuts to any place worth going.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Your attitude, not your aptitude, will determine your altitude.",
  "Work hard in silence, let your success be your noise.",
  "If opportunity doesn't knock, build a door.",
  "Success is walking from failure to failure with no loss of enthusiasm."
];
